In [ ]:
# DATA FRAMES
# when we combine multiple series it becomes data frames.

In [8]:
import numpy as np
import pandas as pd

In [1]:
# CREATING A DATAFRAMES

In [11]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paries', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]

}
df =pd.DataFrame(data)

In [12]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
data_list= {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paries', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]

}
df2 =pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
# SELECTION AND INDEXING OF COLUMNS

In [21]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [24]:
df2['City']

0    New York
1      Paries
2      Berlin
3      London
Name: City, dtype: str

In [25]:
df2['Salary']

0    65000
1    70000
2    62000
3    85000
Name: Salary, dtype: int64

In [26]:
df2['Age']

0    28
1    34
2    29
3    42
Name: Age, dtype: int64

In [28]:
df2[['Name', 'City']]

    Name      City
0   John  New York
1   Anna    Paries
2  Peter    Berlin
3  Linda    London

In [29]:
df2[['Salary','Age']]

   Salary  Age
0   65000   28
1   70000   34
2   62000   29
3   85000   42

In [14]:
# CREATING A NEW COLUMN

In [30]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [31]:
df2["Designation"] = ["Docter", "eng","doctor","eng"]

In [32]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Docter
1   Anna   34    Paries   70000         eng
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000         eng

In [15]:
# REMOVING COLUMNS

In [33]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Docter
1   Anna   34    Paries   70000         eng
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000         eng

In [34]:
df2.drop('Designation',axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [35]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Docter
1   Anna   34    Paries   70000         eng
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000         eng

In [37]:
# to delete permentely will use inplace = 1

In [38]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Docter
1   Anna   34    Paries   70000         eng
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000         eng

In [42]:
df2.drop(["Designation"],axis = 1,inplace = True)

In [43]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [44]:
# to drop rows

In [45]:
df2.drop(0,axis = 0)

    Name  Age    City  Salary
1   Anna   34  Paries   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [46]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
# SELECTING ROWS

In [47]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [48]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [49]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34    Paries   70000

In [50]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
# SELECTING SUNSETS OF ROWS AND COLUMNS

In [51]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [52]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34    Paries   70000

In [53]:
df2.loc[[0,1]][["City", "Salary"]]

       City  Salary
0  New York   65000
1    Paries   70000

In [54]:
df2.loc[[0,1]][["Name", "City"]]

   Name      City
0  John  New York
1  Anna    Paries

In [55]:
df2.loc[[0,1]][["Name", "Age"]]

   Name  Age
0  John   28
1  Anna   34

In [56]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
# CONDITIONAL SELECTIION

In [57]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [58]:
# I ONLY WANT TO SEE WHOSE AGE IS ABOVE 30

In [59]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34  Paries   70000
3  Linda   42  London   85000

In [60]:
# I ONLY WANT WHOSE AGE IS ABOVE 30 AND THERE CITY MUST BE PARIES

In [67]:
df2[(df2["Age"] > 30) & (df2["City"] == 'Paries')]

   Name  Age    City  Salary
1  Anna   34  Paries   70000

In [68]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34    Paries   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000